using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using System.Text.Json;

namespace DtoOrm.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class DtoOrmSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var schemas = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".dtoorm.schema.json", StringComparison.OrdinalIgnoreCase) ||
              file.Path.EndsWith("dtoorm.schema.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, cancellationToken) =>
            {
                var sourceText = file.GetText(cancellationToken);
                if (sourceText is null)
                {
                    return null;
                }

                try
                {
                    return JsonSerializer.Deserialize<DatabaseSchema>(sourceText.ToString(), JsonOptions());
                }
                catch
                {
                    return null;
                }
            });

        context.RegisterSourceOutput(schemas, static (productionContext, schema) =>
        {
            if (schema is null)
            {
                return;
            }

            var source = Generate(schema);
            productionContext.AddSource("DtoOrm.Db.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static JsonSerializerOptions JsonOptions()
        => new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        };

    private static string Generate(DatabaseSchema schema)
    {
        var ns = string.IsNullOrWhiteSpace(schema.Namespace) ? "DtoOrm.Generated" : schema.Namespace!;
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("public static partial class Db");
        sb.AppendLine("{");

        sb.AppendLine("    public static class Tables");
        sb.AppendLine("    {");
        foreach (var table in schema.Tables.OrderBy(t => t.ClrName, StringComparer.Ordinal))
        {
            sb.Append("        public static readonly ")
              .Append(table.ClrName)
              .Append("Table ")
              .Append(table.ClrName)
              .Append(" = new();")
              .AppendLine();
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var table in schema.Tables.OrderBy(t => t.ClrName, StringComparer.Ordinal))
        {
            sb.Append("    public sealed class ")
              .Append(table.ClrName)
              .AppendLine("Table : global::DtoOrm.Core.Table");
            sb.AppendLine("    {");
            sb.Append("        internal ")
              .Append(table.ClrName)
              .Append("Table() : base(")
              .Append(Literal(table.DbName)).Append(", ")
              .Append(Literal(table.ClrName)).Append(", ")
              .Append(Literal(string.IsNullOrWhiteSpace(table.Alias) ? MakeAlias(table.DbName) : table.Alias!))
              .AppendLine(")");
            sb.AppendLine("        {");
            foreach (var column in table.Columns.OrderBy(c => c.Ordinal))
            {
                sb.Append("            ")
                  .Append(column.ClrName)
                  .Append(" = new global::DtoOrm.Core.Column<")
                  .Append(column.ClrType)
                  .Append(">(this, ")
                  .Append(Literal(column.DbName))
                  .Append(", ")
                  .Append(Literal(column.ClrName))
                  .AppendLine(");");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var column in table.Columns.OrderBy(c => c.Ordinal))
            {
                sb.Append("        public global::DtoOrm.Core.Column<")
                  .Append(column.ClrType)
                  .Append("> ")
                  .Append(column.ClrName)
                  .AppendLine(" { get; }");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Literal(string value)
        => "@\"" + value.Replace("\"", "\"\"") + "\"";

    private static string MakeAlias(string name)
    {
        var chars = name.Where(char.IsLetterOrDigit).Take(3).ToArray();
        return chars.Length == 0 ? "t" : new string(chars).ToLowerInvariant();
    }

    private sealed class DatabaseSchema
    {
        public string? Namespace { get; set; }
        public string? Database { get; set; }
        public List<TableSchema> Tables { get; set; } = new List<TableSchema>();
    }

    private sealed class TableSchema
    {
        public string DbName { get; set; } = "";
        public string ClrName { get; set; } = "";
        public string? Alias { get; set; }
        public List<ColumnSchema> Columns { get; set; } = new List<ColumnSchema>();
    }

    private sealed class ColumnSchema
    {
        public string DbName { get; set; } = "";
        public string ClrName { get; set; } = "";
        public string ClrType { get; set; } = "object";
        public int Ordinal { get; set; }
    }
}
